name: dbt_py3.12
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - arrow-cpp=19.0.0
  - aws-c-auth=0.6.19
  - aws-c-cal=0.5.20
  - aws-c-common=0.8.5
  - aws-c-compression=0.2.16
  - aws-c-event-stream=0.2.15
  - aws-c-http=0.6.25
  - aws-c-io=0.13.10
  - aws-c-mqtt=0.7.13
  - aws-c-s3=0.1.51
  - aws-c-sdkutils=0.1.6
  - aws-checksums=0.1.13
  - aws-crt-cpp=0.18.16
  - aws-sdk-cpp=1.11.212
  - blas=1.0
  - boost-cpp=1.82.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - cffi=1.17.1
  - cryptography=44.0.1
  - expat=2.6.4
  - gflags=2.2.2
  - glog=0.5.0
  - google-api-core=2.24.2
  - google-auth=2.38.0
  - google-cloud-core=2.4.3
  - google-cloud-storage=3.1.0
  - google-crc32c=1.6.0
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.69.2
  - grpcio=1.71.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - libabseil=20250127.0
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcrc32c=1.1.2
  - libcurl=8.12.1
  - libevent=2.1.12
  - libffi=3.4.4
  - libgrpc=1.71.0
  - libmpdec=4.0.0
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libthrift=0.15.0
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - numpy=2.2.4
  - numpy-base=2.2.4
  - openssl=3.0.16
  - orc=2.1.1
  - ordered-set=4.1.0
  - pip=25.0
  - proto-plus=1.26.1
  - protobuf=5.29.3
  - pyarrow=19.0.0
  - pycparser=2.21
  - pyopenssl=25.0.0
  - python=3.12.0
  - python-dateutil=2.9.0post0
  - re2=2024.07.02
  - requests=2.32.3
  - setuptools=72.1.0
  - setuptools-scm=8.2.1
  - snappy=1.2.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.12.2
  - utf8proc=2.6.1
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - agate==1.9.1
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - aiosqlite==0.21.0
      - alembic==1.15.2
      - annotated-types==0.7.0
      - anyio==4.9.0
      - apache-airflow==2.10.5
      - apache-airflow-providers-common-compat==1.6.0
      - apache-airflow-providers-common-io==1.5.2
      - apache-airflow-providers-common-sql==1.24.1
      - apache-airflow-providers-fab==1.5.3
      - apache-airflow-providers-ftp==3.12.3
      - apache-airflow-providers-http==5.2.1
      - apache-airflow-providers-imap==3.8.3
      - apache-airflow-providers-smtp==2.0.2
      - apache-airflow-providers-sqlite==4.0.1
      - apispec==6.8.1
      - argcomplete==3.6.1
      - asgiref==3.8.1
      - attrs==24.3.0
      - babel==2.16.0
      - blinker==1.9.0
      - cachelib==0.13.0
      - cachetools==5.5.1
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - clickclick==20.10.2
      - cloudevents==1.11.0
      - colorama==0.4.6
      - colorlog==6.9.0
      - configupdater==3.2
      - connexion==2.14.2
      - cramjam==2.9.1
      - cron-descriptor==1.4.5
      - croniter==6.0.0
      - daff==1.3.46
      - db-dtypes==1.3.1
      - dbt-adapters==1.13.1
      - dbt-bigquery==1.9.1
      - dbt-common==1.14.0
      - dbt-core==1.9.1
      - dbt-extractor==0.5.1
      - dbt-semantic-interfaces==0.7.4
      - decorator==5.1.1
      - deepdiff==7.0.1
      - deprecated==1.2.18
      - deprecation==2.1.0
      - diff-cover==9.2.2
      - dill==0.3.9
      - dnspython==2.7.0
      - email-validator==2.2.0
      - fastparquet==2024.11.0
      - flask==2.2.5
      - flask-appbuilder==4.5.3
      - flask-babel==2.0.0
      - flask-caching==2.3.1
      - flask-jwt-extended==4.7.1
      - flask-limiter==3.12
      - flask-login==0.6.3
      - flask-session==0.5.0
      - flask-sqlalchemy==2.5.1
      - flask-wtf==1.2.2
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - functions-framework==3.8.2
      - gcsfs==2025.2.0
      - google-auth-oauthlib==1.2.1
      - google-cloud-appengine-logging==1.6.0
      - google-cloud-audit-log==0.3.0
      - google-cloud-bigquery==3.29.0
      - google-cloud-dataproc==5.16.0
      - google-cloud-logging==3.11.4
      - google-re2==1.1.20240702
      - greenlet==3.1.1
      - grpc-google-iam-v1==0.14.0
      - grpcio-status==1.69.0
      - gunicorn==23.0.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - idna==3.10
      - importlib-metadata==6.11.0
      - inflection==0.5.1
      - iniconfig==2.0.0
      - isodate==0.6.1
      - itsdangerous==2.2.0
      - jinja2-simple-tags==0.6.1
      - jmespath==1.0.1
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - lazy-object-proxy==1.10.0
      - leather==0.4.0
      - limits==4.4.1
      - linkify-it-py==2.0.3
      - lockfile==0.12.2
      - mako==1.3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - marshmallow-oneofschema==3.1.1
      - marshmallow-sqlalchemy==0.28.2
      - mashumaro==3.14
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - methodtools==0.4.7
      - more-itertools==10.6.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - networkx==3.4.2
      - oauthlib==3.2.2
      - opentelemetry-api==1.31.1
      - opentelemetry-exporter-otlp==1.31.1
      - opentelemetry-exporter-otlp-proto-common==1.31.1
      - opentelemetry-exporter-otlp-proto-grpc==1.31.1
      - opentelemetry-exporter-otlp-proto-http==1.31.1
      - opentelemetry-proto==1.31.1
      - opentelemetry-sdk==1.31.1
      - opentelemetry-semantic-conventions==0.52b1
      - packaging==24.2
      - pandas==2.2.3
      - parsedatetime==2.6
      - pathspec==0.12.1
      - pendulum==3.0.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - prison==0.2.1
      - propcache==0.2.1
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pytest==8.3.4
      - python-certifi-win32==1.6.1
      - python-daemon==3.1.2
      - python-dotenv==1.0.1
      - python-nvd3==0.16.0
      - python-slugify==8.0.4
      - pytimeparse==1.1.8
      - pytz==2024.2
      - pyyaml==6.0.2
      - referencing==0.36.1
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rich==13.9.4
      - rich-argparse==1.7.0
      - rpds-py==0.22.3
      - rsa==4.9
      - setproctitle==1.3.5
      - six==1.17.0
      - snakeviz==2.2.2
      - sniffio==1.3.1
      - snowplow-tracker==1.0.4
      - sqlalchemy==1.4.54
      - sqlalchemy-jsonfield==1.0.2
      - sqlalchemy-utils==0.41.2
      - sqlfluff==3.3.1
      - sqlfluff-templater-dbt==3.3.1
      - sqlparse==0.5.3
      - tabulate==0.9.0
      - tblib==3.0.0
      - tenacity==9.0.0
      - termcolor==2.5.0
      - text-unidecode==1.3
      - time-machine==2.16.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - types-requests==2.32.0.20241016
      - tzdata==2025.1
      - uc-micro-py==1.0.3
      - universal-pathlib==0.2.6
      - urllib3==2.3.0
      - watchdog==6.0.0
      - werkzeug==2.2.3
      - wirerope==1.0.0
      - wrapt==1.17.2
      - wtforms==3.2.1
      - yarl==1.18.3
      - zipp==3.21.0