name: everything_about_python
dependencies:
  - python=3.10.4
  - pip:
      - pygame==2.1.2
      - numpy==1.23.2
      - pandas==1.4.3
      - scipy==1.9.0
      - matplotlib==3.6.1
      - plotly==5.10.0
      - requests==2.28.1
