name: everything_about_python
dependencies:
  - python=3.10.4
  - pip:
      - pygame==2.1.2
      - numpy==1.23.2
      - pandas==1.4.3
      - scipy==1.9.0
      - matplotlib==3.6.1
      - plotly==5.10.0
      - requests==2.28.1
      - django==4.1.3
      - django-bootstrap4==22.3
      - dj-database-url==1.2.0
      - django-heroku==0.3.1
      - gunicorn==20.1.0
      - sqlparse==0.4.3
      - whitenoise==6.2.0
      - psycopg2-binary==2.9.5