name: everything_about_python
dependencies:
  - python=3.12.4
  - pip
  - pip:
      - pandas==2.2.2
      - numpy==2.0.1
      - matplotlib==3.9.1
      - scipy==1.14.0
      - networkx==3.3
      - pytest==8.3.2